#NAME: Arnav Garg
#EMAIL: arnavgrg@ucla.edu
#ID: 304911796

.SILENT:

dist:
	tar -czf lab4a-304911796.tar.gz my_beaglebone.jpg git.png copy.png connected.png build_run.png Makefile README

clean:
	rm -rf *.tar.gz