#NAME: Arnav Garg
#ID: 304911796
#EMAIL: arnavgrg@ucla.edu

.SILENT:

default: clean
	cp lab3b.py lab3b
	chmod +x lab3b lab3b.py

dist:
	tar -czf lab3b-304911796.tar.gz Makefile README lab3b.py

clean:
	rm -rf *.tar.gz lab3b