#NAME: Arnav Garg
#ID: 304911796
#EMAIL: arnavgrg@ucla.edu
#SLIPDAYS: 3

.SILENT:

default:
	gcc -g -Wall -Wextra lab3a.c -o lab3a

dist:
	tar -czf lab3a-304911796.tar.gz ext2_fs.h lab3a.c README Makefile

clean:
	rm -rf lab3a *.o *.tar.gz *.dSYM