#NAME: Arnav Garg
#UID: 304911796
#EMAIL ID: arnavgrg@ucla.edu

.SILENT:

default:
	gcc -g -Wall -Wextra lab3a.c -o lab3a

dist:
	tar -czvf lab3a-304911796.tar.gz ext2_fs.h lab3a.c README Makefile

clean:
	rm -rf lab3a *.o *.tar.gz *.dSYM